export const navItems = [
  { to: "/", label: "Home" },
  { to: "/company", label: "Company" },
  { to: "/custom", label: "Custom Design" },
  { to: "/design-build", label: "Design Build" },
  { to: "/products", label: "Products" },
  { to: "/offers", label: "Offers" },
  { to: "/projects", label: "Projects" },
  { to: "/gallery", label: "Gallery" },
  { to: "/contact", label: "Contact" },
  { to: "/faq", label: "FAQ" },
  { to: "/careers", label: "Careers" },
  { to: "/refer", label: "Refer a Friend" },
  { to: "/csr", label: "CSR" },
  { to: "/annual-return", label: "Annual Return" },
  { to: "/sitemap", label: "Sitemap" },
];
